package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAllPropertiesEquals(Api expected, Api actual) {
        assertApiAutoGeneratedPropertiesEquals(expected, actual);
        assertApiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAllUpdatablePropertiesEquals(Api expected, Api actual) {
        assertApiUpdatableFieldsEquals(expected, actual);
        assertApiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAutoGeneratedPropertiesEquals(Api expected, Api actual) {
        assertThat(expected)
            .as("Verify Api auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiUpdatableFieldsEquals(Api expected, Api actual) {
        assertThat(expected)
            .as("Verify Api relevant properties")
            .satisfies(e -> assertThat(e.getApiNom()).as("check apiNom").isEqualTo(actual.getApiNom()))
            .satisfies(e -> assertThat(e.getApiUrl()).as("check apiUrl").isEqualTo(actual.getApiUrl()))
            .satisfies(e -> assertThat(e.getApiVersion()).as("check apiVersion").isEqualTo(actual.getApiVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiUpdatableRelationshipsEquals(Api expected, Api actual) {}
}
