package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChoixAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChoixAllPropertiesEquals(Choix expected, Choix actual) {
        assertChoixAutoGeneratedPropertiesEquals(expected, actual);
        assertChoixAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChoixAllUpdatablePropertiesEquals(Choix expected, Choix actual) {
        assertChoixUpdatableFieldsEquals(expected, actual);
        assertChoixUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChoixAutoGeneratedPropertiesEquals(Choix expected, Choix actual) {
        assertThat(expected)
            .as("Verify Choix auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChoixUpdatableFieldsEquals(Choix expected, Choix actual) {
        assertThat(expected)
            .as("Verify Choix relevant properties")
            .satisfies(e -> assertThat(e.getChovaleur()).as("check chovaleur").isEqualTo(actual.getChovaleur()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChoixUpdatableRelationshipsEquals(Choix expected, Choix actual) {
        assertThat(expected)
            .as("Verify Choix relationships")
            .satisfies(e -> assertThat(e.getChoquestion()).as("check choquestion").isEqualTo(actual.getChoquestion()))
            .satisfies(
                e -> assertThat(e.getChoquestionSuivante()).as("check choquestionSuivante").isEqualTo(actual.getChoquestionSuivante())
            );
    }
}
