package com.example.myproject.domain;

import static com.example.myproject.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CompanyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyAllPropertiesEquals(Company expected, Company actual) {
        assertCompanyAutoGeneratedPropertiesEquals(expected, actual);
        assertCompanyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyAllUpdatablePropertiesEquals(Company expected, Company actual) {
        assertCompanyUpdatableFieldsEquals(expected, actual);
        assertCompanyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyAutoGeneratedPropertiesEquals(Company expected, Company actual) {
        assertThat(expected)
            .as("Verify Company auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyUpdatableFieldsEquals(Company expected, Company actual) {
        assertThat(expected)
            .as("Verify Company relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getActivity()).as("check activity").isEqualTo(actual.getActivity()))
            .satisfies(e -> assertThat(e.getCamtitre()).as("check camtitre").isEqualTo(actual.getCamtitre()))
            .satisfies(e -> assertThat(e.getCamdatecreation()).as("check camdatecreation").isEqualTo(actual.getCamdatecreation()))
            .satisfies(
                e ->
                    assertThat(e.getCamdatefin())
                        .as("check camdatefin")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getCamdatefin())
            )
            .satisfies(e -> assertThat(e.getCamispub()).as("check camispub").isEqualTo(actual.getCamispub()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyUpdatableRelationshipsEquals(Company expected, Company actual) {
        assertThat(expected)
            .as("Verify Company relationships")
            .satisfies(e -> assertThat(e.getCamUser()).as("check camUser").isEqualTo(actual.getCamUser()))
            .satisfies(e -> assertThat(e.getCamstatus()).as("check camstatus").isEqualTo(actual.getCamstatus()));
    }
}
