package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DialogueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDialogueAllPropertiesEquals(Dialogue expected, Dialogue actual) {
        assertDialogueAutoGeneratedPropertiesEquals(expected, actual);
        assertDialogueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDialogueAllUpdatablePropertiesEquals(Dialogue expected, Dialogue actual) {
        assertDialogueUpdatableFieldsEquals(expected, actual);
        assertDialogueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDialogueAutoGeneratedPropertiesEquals(Dialogue expected, Dialogue actual) {
        assertThat(expected)
            .as("Verify Dialogue auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDialogueUpdatableFieldsEquals(Dialogue expected, Dialogue actual) {
        assertThat(expected)
            .as("Verify Dialogue relevant properties")
            .satisfies(e -> assertThat(e.getDialogueId()).as("check dialogueId").isEqualTo(actual.getDialogueId()))
            .satisfies(e -> assertThat(e.getContenu()).as("check contenu").isEqualTo(actual.getContenu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDialogueUpdatableRelationshipsEquals(Dialogue expected, Dialogue actual) {}
}
