package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntitedetestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntitedetestAllPropertiesEquals(Entitedetest expected, Entitedetest actual) {
        assertEntitedetestAutoGeneratedPropertiesEquals(expected, actual);
        assertEntitedetestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntitedetestAllUpdatablePropertiesEquals(Entitedetest expected, Entitedetest actual) {
        assertEntitedetestUpdatableFieldsEquals(expected, actual);
        assertEntitedetestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntitedetestAutoGeneratedPropertiesEquals(Entitedetest expected, Entitedetest actual) {
        assertThat(expected)
            .as("Verify Entitedetest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntitedetestUpdatableFieldsEquals(Entitedetest expected, Entitedetest actual) {
        assertThat(expected)
            .as("Verify Entitedetest relevant properties")
            .satisfies(e -> assertThat(e.getIdentite()).as("check identite").isEqualTo(actual.getIdentite()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getNombrec()).as("check nombrec").isEqualTo(actual.getNombrec()))
            .satisfies(e -> assertThat(e.getChamb()).as("check chamb").isEqualTo(actual.getChamb()))
            .satisfies(e -> assertThat(e.getChampdate()).as("check champdate").isEqualTo(actual.getChampdate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntitedetestUpdatableRelationshipsEquals(Entitedetest expected, Entitedetest actual) {}
}
