package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FileextraitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileextraitAllPropertiesEquals(Fileextrait expected, Fileextrait actual) {
        assertFileextraitAutoGeneratedPropertiesEquals(expected, actual);
        assertFileextraitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileextraitAllUpdatablePropertiesEquals(Fileextrait expected, Fileextrait actual) {
        assertFileextraitUpdatableFieldsEquals(expected, actual);
        assertFileextraitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileextraitAutoGeneratedPropertiesEquals(Fileextrait expected, Fileextrait actual) {
        assertThat(expected)
            .as("Verify Fileextrait auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileextraitUpdatableFieldsEquals(Fileextrait expected, Fileextrait actual) {
        assertThat(expected)
            .as("Verify Fileextrait relevant properties")
            .satisfies(e -> assertThat(e.getFexidfile()).as("check fexidfile").isEqualTo(actual.getFexidfile()))
            .satisfies(e -> assertThat(e.getFexparent()).as("check fexparent").isEqualTo(actual.getFexparent()))
            .satisfies(e -> assertThat(e.getFexdata()).as("check fexdata").isEqualTo(actual.getFexdata()))
            .satisfies(
                e -> assertThat(e.getFexdataContentType()).as("check fexdata contenty type").isEqualTo(actual.getFexdataContentType())
            )
            .satisfies(e -> assertThat(e.getFextype()).as("check fextype").isEqualTo(actual.getFextype()))
            .satisfies(e -> assertThat(e.getFexname()).as("check fexname").isEqualTo(actual.getFexname()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileextraitUpdatableRelationshipsEquals(Fileextrait expected, Fileextrait actual) {}
}
