package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeAllPropertiesEquals(Groupe expected, Groupe actual) {
        assertGroupeAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeAllUpdatablePropertiesEquals(Groupe expected, Groupe actual) {
        assertGroupeUpdatableFieldsEquals(expected, actual);
        assertGroupeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeAutoGeneratedPropertiesEquals(Groupe expected, Groupe actual) {
        assertThat(expected)
            .as("Verify Groupe auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeUpdatableFieldsEquals(Groupe expected, Groupe actual) {
        assertThat(expected)
            .as("Verify Groupe relevant properties")
            .satisfies(e -> assertThat(e.getGrotitre()).as("check grotitre").isEqualTo(actual.getGrotitre()))
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupeUpdatableRelationshipsEquals(Groupe expected, Groupe actual) {
        assertThat(expected)
            .as("Verify Groupe relationships")
            .satisfies(e -> assertThat(e.getExtendedUser()).as("check extendedUser").isEqualTo(actual.getExtendedUser()));
    }
}
