package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupedecontactAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupedecontactAllPropertiesEquals(Groupedecontact expected, Groupedecontact actual) {
        assertGroupedecontactAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupedecontactAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupedecontactAllUpdatablePropertiesEquals(Groupedecontact expected, Groupedecontact actual) {
        assertGroupedecontactUpdatableFieldsEquals(expected, actual);
        assertGroupedecontactUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupedecontactAutoGeneratedPropertiesEquals(Groupedecontact expected, Groupedecontact actual) {
        assertThat(expected)
            .as("Verify Groupedecontact auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupedecontactUpdatableFieldsEquals(Groupedecontact expected, Groupedecontact actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupedecontactUpdatableRelationshipsEquals(Groupedecontact expected, Groupedecontact actual) {
        assertThat(expected)
            .as("Verify Groupedecontact relationships")
            .satisfies(e -> assertThat(e.getCgrgroupe()).as("check cgrgroupe").isEqualTo(actual.getCgrgroupe()))
            .satisfies(e -> assertThat(e.getContact()).as("check contact").isEqualTo(actual.getContact()));
    }
}
