package com.example.myproject.domain;

import static com.example.myproject.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class OTPStorageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOTPStorageAllPropertiesEquals(OTPStorage expected, OTPStorage actual) {
        assertOTPStorageAutoGeneratedPropertiesEquals(expected, actual);
        assertOTPStorageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOTPStorageAllUpdatablePropertiesEquals(OTPStorage expected, OTPStorage actual) {
        assertOTPStorageUpdatableFieldsEquals(expected, actual);
        assertOTPStorageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOTPStorageAutoGeneratedPropertiesEquals(OTPStorage expected, OTPStorage actual) {
        assertThat(expected)
            .as("Verify OTPStorage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOTPStorageUpdatableFieldsEquals(OTPStorage expected, OTPStorage actual) {
        assertThat(expected)
            .as("Verify OTPStorage relevant properties")
            .satisfies(e -> assertThat(e.getOtsOTP()).as("check otsOTP").isEqualTo(actual.getOtsOTP()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(
                e ->
                    assertThat(e.getOtsdateexpir())
                        .as("check otsdateexpir")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getOtsdateexpir())
            )
            .satisfies(e -> assertThat(e.getIsOtpUsed()).as("check isOtpUsed").isEqualTo(actual.getIsOtpUsed()))
            .satisfies(e -> assertThat(e.getIsExpired()).as("check isExpired").isEqualTo(actual.getIsExpired()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOTPStorageUpdatableRelationshipsEquals(OTPStorage expected, OTPStorage actual) {
        assertThat(expected)
            .as("Verify OTPStorage relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }
}
