package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReferentielAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferentielAllPropertiesEquals(Referentiel expected, Referentiel actual) {
        assertReferentielAutoGeneratedPropertiesEquals(expected, actual);
        assertReferentielAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferentielAllUpdatablePropertiesEquals(Referentiel expected, Referentiel actual) {
        assertReferentielUpdatableFieldsEquals(expected, actual);
        assertReferentielUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferentielAutoGeneratedPropertiesEquals(Referentiel expected, Referentiel actual) {
        assertThat(expected)
            .as("Verify Referentiel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferentielUpdatableFieldsEquals(Referentiel expected, Referentiel actual) {
        assertThat(expected)
            .as("Verify Referentiel relevant properties")
            .satisfies(e -> assertThat(e.getRefCode()).as("check refCode").isEqualTo(actual.getRefCode()))
            .satisfies(e -> assertThat(e.getRefRadical()).as("check refRadical").isEqualTo(actual.getRefRadical()))
            .satisfies(e -> assertThat(e.getRefFrTitle()).as("check refFrTitle").isEqualTo(actual.getRefFrTitle()))
            .satisfies(e -> assertThat(e.getRefArTitle()).as("check refArTitle").isEqualTo(actual.getRefArTitle()))
            .satisfies(e -> assertThat(e.getRefEnTitle()).as("check refEnTitle").isEqualTo(actual.getRefEnTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferentielUpdatableRelationshipsEquals(Referentiel expected, Referentiel actual) {}
}
