package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReponseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseAllPropertiesEquals(Reponse expected, Reponse actual) {
        assertReponseAutoGeneratedPropertiesEquals(expected, actual);
        assertReponseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseAllUpdatablePropertiesEquals(Reponse expected, Reponse actual) {
        assertReponseUpdatableFieldsEquals(expected, actual);
        assertReponseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseAutoGeneratedPropertiesEquals(Reponse expected, Reponse actual) {
        assertThat(expected)
            .as("Verify Reponse auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseUpdatableFieldsEquals(Reponse expected, Reponse actual) {
        assertThat(expected)
            .as("Verify Reponse relevant properties")
            .satisfies(e -> assertThat(e.getRepvaleur()).as("check repvaleur").isEqualTo(actual.getRepvaleur()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseUpdatableRelationshipsEquals(Reponse expected, Reponse actual) {
        assertThat(expected)
            .as("Verify Reponse relationships")
            .satisfies(e -> assertThat(e.getRepquestion()).as("check repquestion").isEqualTo(actual.getRepquestion()))
            .satisfies(e -> assertThat(e.getRepcontact()).as("check repcontact").isEqualTo(actual.getRepcontact()));
    }
}
