package com.example.myproject.domain;

import static com.example.myproject.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class SendSmsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendSmsAllPropertiesEquals(SendSms expected, SendSms actual) {
        assertSendSmsAutoGeneratedPropertiesEquals(expected, actual);
        assertSendSmsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendSmsAllUpdatablePropertiesEquals(SendSms expected, SendSms actual) {
        assertSendSmsUpdatableFieldsEquals(expected, actual);
        assertSendSmsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendSmsAutoGeneratedPropertiesEquals(SendSms expected, SendSms actual) {
        assertThat(expected)
            .as("Verify SendSms auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendSmsUpdatableFieldsEquals(SendSms expected, SendSms actual) {
        assertThat(expected)
            .as("Verify SendSms relevant properties")
            .satisfies(e -> assertThat(e.getSender()).as("check sender").isEqualTo(actual.getSender()))
            .satisfies(e -> assertThat(e.getReceiver()).as("check receiver").isEqualTo(actual.getReceiver()))
            .satisfies(e -> assertThat(e.getMsgdata()).as("check msgdata").isEqualTo(actual.getMsgdata()))
            .satisfies(
                e ->
                    assertThat(e.getSendateEnvoi())
                        .as("check sendateEnvoi")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getSendateEnvoi())
            )
            .satisfies(e -> assertThat(e.getDialogue()).as("check dialogue").isEqualTo(actual.getDialogue()))
            .satisfies(e -> assertThat(e.getIsSent()).as("check isSent").isEqualTo(actual.getIsSent()))
            .satisfies(e -> assertThat(e.getIsbulk()).as("check isbulk").isEqualTo(actual.getIsbulk()))
            .satisfies(e -> assertThat(e.getTitre()).as("check Titre").isEqualTo(actual.getTitre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSendSmsUpdatableRelationshipsEquals(SendSms expected, SendSms actual) {
        assertThat(expected)
            .as("Verify SendSms relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getDestinateur()).as("check destinateur").isEqualTo(actual.getDestinateur()))
            .satisfies(e -> assertThat(e.getDestinataires()).as("check destinataires").isEqualTo(actual.getDestinataires()))
            .satisfies(e -> assertThat(e.getStatut()).as("check statut").isEqualTo(actual.getStatut()));
    }
}
