package com.example.myproject.domain;

import static com.example.myproject.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TokensAppAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokensAppAllPropertiesEquals(TokensApp expected, TokensApp actual) {
        assertTokensAppAutoGeneratedPropertiesEquals(expected, actual);
        assertTokensAppAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokensAppAllUpdatablePropertiesEquals(TokensApp expected, TokensApp actual) {
        assertTokensAppUpdatableFieldsEquals(expected, actual);
        assertTokensAppUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokensAppAutoGeneratedPropertiesEquals(TokensApp expected, TokensApp actual) {
        assertThat(expected)
            .as("Verify TokensApp auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokensAppUpdatableFieldsEquals(TokensApp expected, TokensApp actual) {
        assertThat(expected)
            .as("Verify TokensApp relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getDateExpiration())
                        .as("check dateExpiration")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getDateExpiration())
            )
            .satisfies(e -> assertThat(e.getToken()).as("check token").isEqualTo(actual.getToken()))
            .satisfies(e -> assertThat(e.getIsExpired()).as("check isExpired").isEqualTo(actual.getIsExpired()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTokensAppUpdatableRelationshipsEquals(TokensApp expected, TokensApp actual) {}
}
