package com.example.myproject.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserTokenApiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenApiAllPropertiesEquals(UserTokenApi expected, UserTokenApi actual) {
        assertUserTokenApiAutoGeneratedPropertiesEquals(expected, actual);
        assertUserTokenApiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenApiAllUpdatablePropertiesEquals(UserTokenApi expected, UserTokenApi actual) {
        assertUserTokenApiUpdatableFieldsEquals(expected, actual);
        assertUserTokenApiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenApiAutoGeneratedPropertiesEquals(UserTokenApi expected, UserTokenApi actual) {
        assertThat(expected)
            .as("Verify UserTokenApi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenApiUpdatableFieldsEquals(UserTokenApi expected, UserTokenApi actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenApiUpdatableRelationshipsEquals(UserTokenApi expected, UserTokenApi actual) {
        assertThat(expected)
            .as("Verify UserTokenApi relationships")
            .satisfies(e -> assertThat(e.getApi()).as("check api").isEqualTo(actual.getApi()))
            .satisfies(e -> assertThat(e.getToken()).as("check token").isEqualTo(actual.getToken()))
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()));
    }
}
